module.exports = {
  ACCESS_TOKEN_SECRET: 'i19rhifnafhasopjfnsniGNP',
  ACCESS_TOKEN_EXPIRY: '900s',
  ACCESS_TOKEN_COOKIE_EXPIRY: 15 * 60,
  REFRESH_TOKEN_SECRET: 'HQ398HFIOQASFPSA9JGASG0IFAF',
  REFRESH_TOKEN_EXPIRY: '24h',
  REFRESH_TOKEN_COOKIE_EXPIRY: 24 * 60 * 60,
  SESSION_EXPIRY: 30,
}
